### ISSUE TITLE
Determine Color scheme for the project

### ISSUE THREAD

**Issue by croberts808** [comp426-2023-spring/a99-TeamNoTeam#7]
https://coolors.co/

**Comment by sadieamato** [comment]
![Image](https://user-images.githubusercontent.com/77795947/230131537-42be6bf2-e97f-40a9-9baf-59d49a8e7935.png)

One option.. I figured at least one part could be carolina blue

**Comment by croberts808** [comment]
I think using Tar Heel Blue is a good idea! I used [this site](https://mycolor.space/?hex=%234B9CD3&sub=1) to generate color palettes with the official UNC blue hex code. I like these and yours so if anyone feels strongly, pick one!

![Image](https://user-images.githubusercontent.com/77806710/230133173-af389f12-65cf-470a-b7f4-0d593731604b.png)
![Image](https://user-images.githubusercontent.com/77806710/230133174-d4f66666-17f1-4a01-b039-c1cbe13b6b9f.png)
![Image](https://user-images.githubusercontent.com/77806710/230133175-0f7c71f7-2a42-4d48-b426-2c10265b5531.png)

**Comment by baileymeredith** [comment]
I really like the matching gradient palette but may be biased because I like purple haha... the generic gradient is also cute! I don't mind too much which palette we use though as long as it has the unc blue color.

**Comment by sadieamato** [comment]
I like the matching gradient too! I think we can go with that one then.
